version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27018:27017
    # if I had to add authentication I would do it like this:
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=rootuser
    #   - MONGO_INITDB_ROOT_PASSWORD=rootpass
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8082:8081
    links:
      - mongo
    environment:
      # if I had to add authentication I would do it like this:
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongo
    restart: always

networks:
  default:
    external: true
    name: mongo-express-network