version: "3.8"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      ADMINER_DEFAULT_SERVER: db
    depends_on: 
      - db

networks:
  default:
    external: true
    name: quizapp-network